version: '3'
services:
  nodejs-app:
    build: .
    container_name: nodejs-app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - local-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-network

volumes:
  postgres-data:

networks:
  local-network:
    driver: bridge